### ISSUE TITLE
typo in file name found

### ISSUE THREAD

**Issue by TiloNN** [intranda/goobi-viewer-theme-reference#1]
https://github.com/intranda/goobi-viewer-theme-reference/blob/ecd4d5cd91c2e6a9f0aa0bd8e68991454b3e2d13/goobi-viewer-theme-reference/WebContent/resources/themes/reference/css/less/constructor.less#L178

Constructor references a wrong file name.
Should be a h in lower case.
`@import "cms/contentComponents/highlightedObject.less"; `

Just checked the develop branch.
Same problem there.

Do you get noticed when I report this in this way?
Was the easiest way for me.

Greetings

**Comment by TiloNN** [comment]
pull request requested :)
https://github.com/intranda/goobi-viewer-theme-reference/pull/2

**Comment by janvonde** [comment]
merged. thanks! :slightly_smiling_face:
